name: Build and Publish

on:
  push:
    branches:
      - master
  release:
    types:
      - published
      - prereleased    

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   ssh-key: "${{ secrets.COMMIT_KEY }}"

      # Set up Node.js environment
      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18' # Set to your required Node.js version

      - name: Install dependencies
        run: npm ci

      - run: npm run lint
      - run: npm run test
      - run: npm run build

      # # Build the project
      # - name: Build TypeScript project
      #   run: npm run build

      # # Run tests (Optional, if you have tests)
      # - name: Run tests
      #   run: npm test

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # publish:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'  # Only run on the main branch

  #   steps:
  #     # Checkout the code
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # Set up Node.js environment
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     # Install dependencies
  #     - name: Install dependencies
  #       run: npm install

  #     # Build the project (if needed)
  #     - name: Build project
  #       run: npm run build

  #     # Publish to npm
  #     - name: Publish to npm
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
